# Generated by Django 4.0.5 on 2023-12-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='upload')),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sub_category',
            field=models.ManyToManyField(to='blurb.subsubcategory'),
        ),
    ]
