# Generated by Django 4.0.5 on 2023-12-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blurb', '0002_subsubcategory_subcategory_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='market',
            field=models.ManyToManyField(to='blurb.market'),
        ),
    ]
