# Generated by Django 4.0.5 on 2023-12-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blurb', '0004_products_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='short_Descriptions',
            new_name='short_descriptions',
        ),
    ]
